<?php

require_once dirname(__FILE__) . '/../../../lib/classes/arr.php';

/**
 * Test class for Arr.
 * Generated by PHPUnit on 2010-11-18 at 09:01:23.
 */
class ArrTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Arr
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Arr;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement testLowerKeys().
	 */
	public function testLowerKeys()
	{
		$arr = array('LoWeR' => 1, 'lower' => 1, 'LOWER' => 1);
		$arr = Arr::LowerKeys($arr);
		foreach (array_keys($arr) as $k)
			$this->assertEquals('lower', $k);
	}

	/**
	 * @todo Implement testYank().
	 */
	public function testYank()
	{
		$yanked = array('yanked' => 'test');
		Arr::Yank($yanked, 'yanked');
		$this->assertEquals(false, array_key_exists('yanked', $yanked));
	}

	/**
	 * @todo Implement testGetMask().
	 */
	public function testGetMask()
	{
		$arr = array(1, 2);
		$this->assertEquals(3, Arr::GetMask($arr));
	}

	public function testARKSort()
	{
		$arr['zxc']['zxc'] = 1;
		$arr['zxc']['asd'] = 2;
		$arr['asd'] = 3;
		Arr::ARKSort($arr);
		$keys1 = array_keys($arr);
		$keys2 = array_keys($arr['zxc']);
		$this->assertEquals('asd', $keys1[0]);
		$this->assertEquals('asd', $keys2[0]);
		$this->assertEquals('zxc', $keys2[1]);
	}
}

?>
