<?php
require_once dirname(__FILE__) . '/../../../lib/classes/FileManager.php';

/**
 * Test class for FileInfo.
 * Generated by PHPUnit on 2010-11-18 at 22:30:17.
 */
class FileInfoTest extends PHPUnit_Framework_TestCase
{
	public function testFileInfo()
	{
	}
}

?>
