<?php
require_once dirname(__FILE__) . '/../../../lib/classes/FileManager.php';

/**
 * Test class for FileManager.
 * Generated by PHPUnit on 2010-11-18 at 22:30:25.
 */
class FileManagerTest extends PHPUnit_Framework_TestCase
{
	public function testFileManager()
	{
		$fm = new FileManager('test', __DIR__, array('Default'));
		$fm->Prepare();
		$fm->Get();
	}
}

?>
