<?php
require_once dirname(__FILE__) . '/../../../lib/classes/FileManager.php';

/**
 * Test class for FileInfo.
 * Generated by PHPUnit on 2010-11-18 at 22:30:17.
 */
class FileInfoTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var FileInfo
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new FileInfo('.');
		FileInfo::GetFilter($this->object, '.', array('FilterDefault'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFilter().
	 */
	public function testGetFilter()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBit().
	 */
	public function testGetBit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSaveInfo().
	 */
	public function testSaveInfo()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
