<?php
require_once dirname(__FILE__) . '/../../../lib/classes/File.php';

/**
 * Test class for File.
 * Generated by PHPUnit on 2011-01-04 at 21:18:28.
 */
class FileTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var File
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new File;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @todo Implement testPregRename().
	 */
	public function testPregRename()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testResizeImage().
	 */
	public function testResizeImage()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFile().
	 */
	public function testGetFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testExt().
	 */
	public function testExt()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDelTree().
	 */
	public function testDelTree()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDelEmpty().
	 */
	public function testDelEmpty()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsIn().
	 */
	public function testIsIn()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSecurePath().
	 */
	public function testSecurePath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testComb().
	 */
	public function testComb()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStringToSize().
	 */
	public function testStringToSize()
	{
		$this->assertEquals(204800, File::StringToSize('200K'));
	}

	/**
	 * @todo Implement testSizeToString().
	 */
	public function testSizeToString()
	{
		$this->assertEquals('64 KB', File::SizeToString(65536));
		$this->assertEquals('32 MB', File::SizeToString(33552432));
		$this->assertEquals('976.32 MB', File::SizeToString(1023741824));
	}
}

?>
