<?php

require_once dirname(__FILE__) . '/../../../lib/classes/file_info.php';

/**
 * Test class for FileInfo.
 * Generated by PHPUnit on 2011-02-21 at 10:35:26.
 */
class FileInfoTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FileInfo
	 */
	protected $object;

	protected function setUp() {
		$this->object = new FileInfo(__FILE__);
	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString() {
		$this->assertEquals((string)$this->object, 'FileInfoTest.php');
	}

	/**
	 * @todo Implement testGetBit().
	 */
	public function testGetBit() {
		$exp = preg_split('#/|\\\#', $this->object->path);
		$this->assertEquals('classes', $this->object->GetBit(count($exp) - 2));
	}

	public function testSaveInfo()
	{
		$this->object->SaveInfo();
		unlink(dirname(__FILE__).'/.FileInfoTest.php');
	}
}

?>
