<?php

require_once dirname(__FILE__) . '/../../../lib/classes/hm.php';

/**
 * Test class for HTML.
 * Generated by PHPUnit on 2010-11-18 at 20:53:35.
 */
class HMTest extends PHPUnit_Framework_TestCase
{
	protected function setUp()
	{
	}

	public function testCleanID()
	{
		$this->assertEquals('a__22', HM::CleanID('a [22]'));
	}

	public function testGetAttribs()
	{
		$this->assertEquals(' test="1"', HM::GetAttribs(array('test' => 1)));
		$this->assertEquals(' test="1"', HM::GetAttribs('test="1"'));
	}

	public function testParseAttribs()
	{
		$arr = HM::ParseAttribs('test="1"');
		$this->assertEquals('1', $arr['TEST']);
	}

	public function testAttribAppend()
	{
		$atrs['CLASS'] = 'first';
		HM::AttribAppend($atrs, 'class', 'additional');
		$this->assertEquals('first additional', $atrs['CLASS']);
		$atrs = array();
		HM::AttribAppend($atrs, 'class', 'additional');
		$this->assertEquals('additional', $atrs['CLASS']);
	}

	public function testURL()
	{
		$url = HM::URL('http://www.google.com', array('test' => 'something'));
		$this->assertEquals('http://www.google.com?test=something', $url);
	}

	public function testParseURL()
	{
		//$dat = HM::ParseURL('http://www.google.com?test=testing');
	}
}

?>
