<?php

require_once dirname(__FILE__) . '/../../../lib/classes/HTML.php';

/**
 * Test class for HTML.
 * Generated by PHPUnit on 2010-11-18 at 20:53:35.
 */
class HTMLTest extends PHPUnit_Framework_TestCase
{
	protected function setUp()
	{
	}

	public function testCleanID()
	{
		$this->assertEquals('a__22', HTML::CleanID('a [22]'));
	}

	public function testGetAttribs()
	{
		$this->assertEquals(' test="1"', HTML::GetAttribs(array('test' => 1)));
		$this->assertEquals(' test="1"', HTML::GetAttribs('test="1"'));
	}

	public function testParseAttribs()
	{
		$arr = HTML::ParseAttribs('test="1"');
		$this->assertEquals('1', $arr['test']);
	}
}

?>
