<?php

require_once dirname(__FILE__) . '/../../../lib/classes/layered_output.php';

/**
 * Test class for LayeredOutput.
 * Generated by PHPUnit on 2010-11-18 at 20:04:23.
 */
class LayeredOutputTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var LayeredOutput
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new LayeredOutput;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement testCreateBuffer().
	 */
	public function testCreateBuffer()
	{
		$this->assertEquals(count($this->object->outs), 1);
		$this->object->CreateBuffer();
		$this->assertEquals(count($this->object->outs), 2);
	}

	/**
	 * @todo Implement testOut().
	 */
	public function testOut()
	{
		$this->object->Out('Test');
		$this->assertEquals('Test', $this->object->Get());
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet()
	{
		$this->object->Out('Test');
		$this->assertEquals('Test', $this->object->Get());
	}

	/**
	 * @todo Implement testFlushBuffer().
	 */
	public function testFlushBuffer()
	{
		$this->object->Out('Test');
		$this->assertEquals('Test', $this->object->FlushBuffer());
		$this->assertEquals(0, $this->object->layer);
	}
}

?>
