<?php

require_once dirname(__FILE__) . '/../../../lib/classes/module.php';
require_once dirname(__FILE__) . '/../../../lib/classes/utility.php';

/**
 * Test class for Module.
 * Generated by PHPUnit on 2010-11-23 at 02:09:49.
 */
class ModuleTest extends PHPUnit_Framework_TestCase
{
	public function testModule()
	{
		Module::Initialize(realpath(dirname(__FILE__).'../../../'), true);

		require_once(__DIR__.'/../../../h_main.php');
		require_once(__DIR__.'/../../../lib/modules/article/article.php');
		Module::Register('ModArticles');
		$temp = <<<EOF
<html doctype="trans">
<body>
<block name="default" />
</body>
</html>
EOF;
		Module::RunString($temp);
	}
}

?>
