<?php

require_once dirname(__FILE__) . '/../../../lib/classes/str.php';

/**
 * Test class for Str.
 * Generated by PHPUnit on 2010-11-18 at 20:12:06.
 */
class StrTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @todo Implement testPlural().
	 */
	public function testPlural()
	{
		$this->assertEquals('Users', Str::Plural('User'));
		$this->assertEquals('Useries', Str::Plural('Usery'));
		$this->assertEquals(null, Str::Plural(''));
	}

	/**
	 * @todo Implement testChomp().
	 */
	public function testChomp()
	{
		$this->assertEquals('A string ...',
			Str::Chomp('A string of more than 10 characters', 10));
		$this->assertEquals('A string', Str::Chomp('A string'));
	}

	/**
	 * @todo Implement testRandomString().
	 */
	public function testRandomString()
	{
		Str::Random(20);
	}

	public function teststrmatch()
	{
		$this->assertEquals(strmatch('test', 'test'), true);
	}
}

?>
