<?php
require_once dirname(__FILE__) . '/../../../lib/classes/tree_node.php';

/**
 * Test class for TreeNode.
 * Generated by PHPUnit on 2010-11-18 at 21:28:00.
 */
class TreeNodeTest extends PHPUnit_Framework_TestCase
{
	public function testTreeNode()
	{
		$tn = new TreeNode('parent', 'data');
		$tn->AddChild(new TreeNode('child', 'cdata'));
		TreeNode::AddNodes($tn, array('P' => 'K'));
		$this->assertEquals('data', $tn->Find('cdata')->parent->id);
		$tn->Dump();
		$tn->Collapse();
		TreeNode::GetUL($tn);
		TreeNode::GetTree($tn, 'Test');

		$atree['Test'] = 'top level';
		$atree['test']['Test2'] = 'lower level';
		TreeNode::FromArray($tn, $atree);
	}
}

?>
