<?php
require_once dirname(__FILE__) . '/../../../lib/classes/TreeNode.php';

/**
 * Test class for TreeNode.
 * Generated by PHPUnit on 2010-11-18 at 21:28:00.
 */
class TreeNodeTest extends PHPUnit_Framework_TestCase
{
	public function testAddChild()
	{
		$tn = new TreeNode('parent', 'data');
		$tn->AddChild(new TreeNode('child', 'cdata'));
		$this->assertEquals('data', $tn->Find('cdata')->parent->id);
	}

	/**
	 * @todo Implement testIndex().
	 */
	public function testIndex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIndex().
	 */
	public function testGetIndex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFind().
	 */
	public function testFind()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDump().
	 */
	public function testDump()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddNodes().
	 */
	public function testAddNodes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCollapse().
	 */
	public function testCollapse()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUL().
	 */
	public function testGetUL()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetTree().
	 */
	public function testGetTree()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFromArray().
	 */
	public function testFromArray()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
