<?php

require_once dirname(__FILE__) . '/../../../../lib/classes/data/database.php';
require_once dirname(__FILE__) . '/../../../../lib/classes/data/data_set.php';
require_once dirname(__FILE__) . '/../../../../lib/modules/editor_data/editor_data.php';

/**
 * Test class for EditorData.
 * Generated by PHPUnit on 2010-11-18 at 15:39:59.
 */
class EditorDataTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var EditorData
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$db = new Database();
		$ds = new DataSet($db, 'test', 'tst_id');
		$ds->FieldInputs = array(
			'tst_name' => new FormInput('Name')
		);
		$ds->DisplayColumns = array(
			'tst_name' => new DisplayColumn('Name')
		);
		$this->object = new EditorData('editor_name', $ds);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement testAddHandler().
	 */
	public function testAddHandler()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepare().
	 */
	public function testPrepare()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetSelArray().
	 */
	public function testGetSelArray()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetSelMask().
	 */
	public function testGetSelMask()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBuildTree().
	 */
	public function testBuildTree()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFixTree().
	 */
	public function testFixTree()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSortByChild().
	 */
	public function testSortByChild()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetTable().
	 */
	public function testGetTable()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddRows().
	 */
	public function testAddRows()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetForm().
	 */
	public function testGetForm()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetForms().
	 */
	public function testGetForms()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testTagForms().
	 */
	public function testTagForms()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testTagSearch().
	 */
	public function testTagSearch()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testReset().
	 */
	public function testReset()
	{
		$this->object->Reset();
	}
}

?>
