<?php

require_once dirname(__FILE__) . '/../../../../lib/classes/module.php';
require_once dirname(__FILE__) . '/../../../../lib/classes/data/database.php';
require_once dirname(__FILE__) . '/../../../../lib/classes/data/data_set.php';
require_once dirname(__FILE__) . '/../../../../lib/modules/editor_data/editor_data.php';

require_once(__DIR__.'/../../../../h_main.php');

/**
 * Test class for EditorData.
 * Generated by PHPUnit on 2010-11-18 at 15:39:59.
 */
class EditorDataTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var EditorData
	 */
	protected $object;

	protected function setUp()
	{
		global $_d;

		Module::Initialize(__DIR__, true);

		$url = parse_url($_d['settings']['database']);
		$url['path'] = '/temp';
		$target = http_build_url($url);

		$db = new Database();
		$db->Open($target, true);

		$sqlCreateTable = <<<EOF
CREATE TABLE IF NOT EXISTS `test` (
	`tst_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`tst_parent` INT UNSIGNED,
	`tst_name` VARCHAR(255),
	PRIMARY KEY (`tst_id`)
)
EOF;

		$db->Query($sqlCreateTable);

		$ds = new DataSet($db, 'test', 'tst_id');
		$ds->FieldInputs = array(
			'tst_name' => new FormInput('Name')
		);
		$ds->DisplayColumns = array(
			'tst_name' => new DisplayColumn('Name')
		);
		$ds->Add(array('tst_name' => 'Hello.'));
		$this->object = new EditorData('editor_name', $ds);
	}

	public function testMain()
	{
		$this->object->Active = true;
		$this->object->Behavior->Search = false;
		$this->object->Prepare();
		$this->object->Get();
	}

	public function testAddHandler()
	{
		$this->object->AddHandler(new TestEditorHandler());
	}

	public function testReset()
	{
		$this->object->Reset();
	}
}

class TestEditorHandler extends EditorHandler
{
}