<?php

require_once dirname(__FILE__) . '/../../../../lib/modules/file_manager/file_manager.php';

/**
 * Test class for FileManager.
 * Generated by PHPUnit on 2011-02-16 at 13:59:19.
 */
class FileManagerTest extends PHPUnit_Framework_TestCase
{
	public function testFileManager() {
		$fm = new FileManager();
		$fm->Active = true;
		$fm->Root = __DIR__.'/../../../../test';
		$fm->Prepare();
		$fm->Get();
	}
}

?>
