<?php

require_once dirname(__FILE__) . '/../../../../lib/modules/file_manager/filter_default.php';

/**
 * Test class for FilterDefault.
 * Generated by PHPUnit on 2012-08-01 at 23:54:35.
 */
class FilterDefaultTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FilterDefault
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FilterDefault;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers FilterDefault::UpdateMTime
	 * @todo Implement testUpdateMTime().
	 */
	public function testUpdateMTime() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFPrepare
	 * @todo Implement testFFPrepare().
	 */
	public function testFFPrepare() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFGetInfo
	 * @todo Implement testFFGetInfo().
	 */
	public function testFFGetInfo() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFGetOptions
	 * @todo Implement testFFGetOptions().
	 */
	public function testFFGetOptions() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFGetQuickOpts
	 * @todo Implement testFFGetQuickOpts().
	 */
	public function testFFGetQuickOpts() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFGetQuickOptFinal
	 * @todo Implement testFFGetQuickOptFinal().
	 */
	public function testFFGetQuickOptFinal() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFUpload
	 * @todo Implement testFFUpload().
	 */
	public function testFFUpload() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFRename
	 * @todo Implement testFFRename().
	 */
	public function testFFRename() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFUpdated
	 * @todo Implement testFFUpdated().
	 */
	public function testFFUpdated() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFDelete
	 * @todo Implement testFFDelete().
	 */
	public function testFFDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFInstall
	 * @todo Implement testFFInstall().
	 */
	public function testFFInstall() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers FilterDefault::FFCleanup
	 * @todo Implement testFFCleanup().
	 */
	public function testFFCleanup() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
