<?php
require_once dirname(__FILE__) . '/../../lib/classes/present/Calendar.php';

/**
 * Test class for CalendarDay.
 * Generated by PHPUnit on 2010-11-18 at 05:05:40.
 */
class CalendarDayTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var CalendarDay
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CalendarDay;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
}

?>
