<?php

require_once(__DIR__.'/../../../../lib/classes/data/DataSet.php');
require_once(__DIR__.'/../../../../h_main.php');

/**
 * Test class for DataSet.
 * Generated by PHPUnit on 2010-11-20 at 10:53:17.
 */
class DataSetTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var DataSet
	 */
	protected $object;

	protected function setUp()
	{
		global $_d;

		# Find our database for $target

		$url = parse_url($_d['settings']['database']);
		$url['path'] = '/temp';
		$target = http_build_url($url);

		# Open our database

		$db = new Database();
		$db->Open($target, true);

		# Create our dataset

		$this->object = new DataSet($db, 'test', 'tst_id');
		$dsChild = new DataSet($db, 'test', 'tst_id');
		$dsChild->Shortcut = 'tchild';
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function testDataSet()
	{
		$sqlCreateTable = <<<EOF
CREATE TABLE IF NOT EXISTS `test` (
	`tst_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`tst_parent` INT UNSIGNED,
	`tst_name` VARCHAR(255),
	PRIMARY KEY (`tst_id`)
)
EOF;

		$this->object->database->Query($sqlCreateTable);

		# Creates

		$this->object->Add(array('tst_name' => 'test'));

		# Updates

		$this->object->Update(array('tst_name' => 'test'),
			array('tst_name' => 'test2'));

		# Gets

		$q['match']['tst_id'] = Database::SqlGreater(5);
		$q['match']['tst_parent'] = 0;
		$q['order']['tst_id'] = 'ASC';
		$q['limit'] = array(0, 10);
		$this->object->Get($q);

		# Cleanup

		$this->object->Remove(array('tst_name' => 'test'));
		$this->object->database->DropTable('test');
		$this->object->database->Drop();
	}

	public function testProcessVal()
	{
		$testIn = Database::SqlNot(
			Database::SqlIn(
				array(1, 2, 'three', 'four')
			)
		);

		$this->assertEquals("NOT IN('1', '2', 'three', 'four')",
			$this->object->ProcessVal($testIn));
	}
}

?>
