<?php

require_once dirname(__FILE__) . '/../../../../lib/modules/gallery/gallery.php';

/**
 * Test class for Gallery.
 * Generated by PHPUnit on 2012-08-01 at 23:56:33.
 */
class GalleryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @covers Gallery
	 * @todo Implement testTagHeader().
	 */
	public function testGallery()
	{
		Module::Initialize(__DIR__, true);
		$gal = new Gallery();
		$gal->Active = true;
		$gal->Root = __DIR__.'/../../../../test';
		$gal->Prepare();
		$gal->Get();
	}
}

?>
