<?php

require_once dirname(__FILE__) . '/../../../../lib/modules/filemanager/FileManager.php';

/**
 * Test class for FileManagerBehavior.
 * Generated by PHPUnit on 2011-02-16 at 13:59:16.
 */
class FileManagerBehaviorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FileManagerBehavior
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FileManagerBehavior;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testAvailable().
	 */
	public function testAvailable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMassAvailable().
	 */
	public function testMassAvailable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAllowAll().
	 */
	public function testAllowAll() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetOptions().
	 */
	public function testGetOptions() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdate().
	 */
	public function testUpdate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
