<?php

require_once dirname(__FILE__) . '/../../../../lib/modules/filemanager/FileManager.php';

/**
 * Test class for FileManagerView.
 * Generated by PHPUnit on 2011-02-16 at 13:59:12.
 */
class FileManagerViewTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FileManagerView
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FileManagerView;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testGetCaption().
	 */
	public function testGetCaption() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
