<?php
require_once dirname(__FILE__) . '/../../../../lib/classes/present/EditorData.php';

/**
 * Test class for DisplayColumn.
 * Generated by PHPUnit on 2010-11-18 at 15:40:02.
 */
class DisplayColumnTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var DisplayColumn
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new DisplayColumn;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
}

?>
