<?php

require_once dirname(__FILE__) . '/../../../../lib/classes/present/form_option.php';
require_once dirname(__FILE__) . '/../../../../lib/classes/present/form_input.php';

/**
 * Test class for FormOption.
 * Generated by PHPUnit on 2012-08-02 at 00:55:19.
 */
class FormOptionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FormOption
	 */
	protected $object;

	/** Before each test */
	protected function setUp() {
		$this->object = new FormOption('Option', true);
		$this->object->valu = 'val';
	}

	/**
	 * @covers FormOption::__tostring
	 */
	public function test__tostring() {
		$this->assertEquals('Option', (string)$this->object);
	}

	public function testRenderCheck()
	{
		$this->assertEquals('<input type="checkbox" value="val" checked="checked" /> <label for="">Option</label><br />', $this->object->RenderCheck());
	}

	public function testRender()
	{
		$this->assertEquals('<option value="val" selected="selected">Option</option>', $this->object->Render());
	}

	public function testFromData()
	{
		$rows[] = array('tst_id' => 1, 'tst_name' => 'Test 1');
		$rows[] = array('tst_id' => 2, 'tst_name' => 'Test 2');

		FormOption::FromData($rows, 'tst_name', 'tst_id', 1, 'Blank');
	}

	function testGetChecks()
	{
		$arr['Test']['Child'] = 'Testing';
		$opts = FormOption::FromArray($arr);
		$atrs['NAME'] = 'test';
		FormOption::GetChecks($atrs, $opts, 1);
	}

	function testCBSelect()
	{
		$col = 'tst_name';

		$ds = new stdClass();
		$ds->FieldInputs[$col] = new FormInput('Test Name', 'test', $col);

		$icol = 'tst_id';

		$item[$icol] = '1';
		$item[$col] = 'Example Name';

		$this->assertEquals('1', FormOption::CBSelect($ds, $item, $icol, $col));
	}
}
