<?php

require_once dirname(__FILE__) . '/../../../../lib/classes/FileManager.php';
require_once dirname(__FILE__) . '/../../../../lib/classes/present/EditorData.php';

/**
 * Test class for HandlerFile.
 * Generated by PHPUnit on 2010-11-18 at 15:39:54.
 */
class HandlerFileTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var HandlerFile
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$fm = new FileManager('fman', '.');
		$this->object = new HandlerFile($fm, '.');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @todo Implement testCreate().
	 */
	public function testCreate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreated().
	 */
	public function testCreated()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
