<?php
require_once dirname(__FILE__) . '/../../../../lib/classes/present/template.php';

/**
 * Test class for VarParser.
 * Generated by PHPUnit on 2010-11-18 at 21:33:59.
 */
class VarParserTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var VarParser
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new VarParser;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement testParseVars().
	 */
	public function testParseVars()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testVar_parser().
	 */
	public function testVar_parser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFindVar().
	 */
	public function testFindVar()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
